In [1]:
from collections import namedtuple

In [7]:
import os

In [3]:
os.getcwd()

'd:\\ML Projects\\house_price_prediction\\notebook'

In [6]:
import sys

In [3]:
os.getcwd()

'd:\\ML Projects\\house_price_prediction\\notebook'

In [4]:
os.chdir("d:\\ML Projects\\house_price_prediction")

In [5]:
os.getcwd()

'd:\\ML Projects\\house_price_prediction'

In [8]:
from Preactice.practice1 import logging

In [22]:
class Famile:
     
    logging.info("Creating a class name Family")
    def __init__(self,name,age,health):
        
        self.name = name
        self.age = age
        self.health = health
        logging.info("init constructor working properly")
    def GrandParent(self):
        logging.info("Created a method inside Famil class")
        try:
            raise Excepsion_hendler("This is a self generated Exception to check Exception hendler")
            logging.info("This function will return the data for Grandparent of family")
            return "Hello my name is Piter and you can get my data here"
            #raise Exc("This is self generated exception")
        except Exception as e:
            housing = Excepsion_hendler(e,sys)
            logging.info(housing.error_message)
            

In [23]:
inform = Famile("Piter",78,"Good")

In [24]:
inform.health

'Good'

In [25]:
inform.age

78

In [26]:
inform.name

'Piter'

In [27]:
inform.GrandParent()

In [21]:
os.getcwd()

'd:\\ML Projects\\house_price_prediction'

In [24]:
import sys

In [9]:
from Preactice.practice2_exc import Excepsion_hendler

In [26]:
from Preactice.practice3 import HousingException

In [15]:
import sys

In [2]:
os.getcwd()

'd:\\ML Projects\\house_price_prediction\\notebook'

In [4]:
os.chdir("d:\\ML Projects\\house_price_prediction")

In [5]:
os.getcwd()

'd:\\ML Projects\\house_price_prediction'

In [6]:
os.listdir()

['.dockerignore',
 '.git',
 '.github',
 '.gitignore',
 'app.py',
 'config',
 'demo.py',
 'Dockerfile',
 'house_price_prediction.egg-info',
 'housing',
 'housing_logs',
 'LICENSE',
 'notebook',
 'Preactice',
 'README.md',
 'requirements.txt',
 'setup.py',
 'venv']

In [7]:
os.listdir("config")

['config.yaml', 'schema.yaml']

In [8]:
os.chdir("d:\\ML Projects\\house_price_prediction\\config")

In [9]:
os.listdir()

['config.yaml', 'schema.yaml']

In [11]:
config = os.path.join("d:\\ML Projects\\house_price_prediction\\config")

In [12]:
config

'd:\\ML Projects\\house_price_prediction\\config'

In [13]:
os.listdir(config)

['config.yaml', 'schema.yaml']

In [52]:
from housing.constant import *

In [19]:
config 

'd:\\ML Projects\\house_price_prediction\\config'

In [25]:
os.getcwd()

'd:\\ML Projects\\house_price_prediction'

In [24]:
os.chdir("d:\\ML Projects\\house_price_prediction")

In [7]:
config_file_path = os.path.join("config","config.yaml")

In [8]:
config_file_path

'config\\config.yaml'

In [9]:
os.path.exists(config_file_path)

True

In [10]:
import yaml

In [11]:
config_info = None
with open(config_file_path,"rb") as f:
    config_info = yaml.safe_load(f)

In [12]:
config_info

{'training_pipeline_config': {'pipeline_name': 'housing',
  'artifact_dir': 'artifact'},
 'data_ingestion_config': {'dataset_download_url': 'https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.tgz',
  'raw_data_dir': 'raw_data',
  'tgz_download_dir': 'tgz_data',
  'ingested_dir': 'ingested_data',
  'ingested_train_dir': 'train',
  'ingested_test_dir': 'test'},
 'data_validation_config': {'schema_dir': 'config',
  'schema_file_name': 'schema.yaml',
  'report_file_name': 'report.json',
  'report_page_file_name': 'report.html'},
 'data_transformation_config': {'add_bedroom_per_room': True,
  'transformed_dir': 'transformed_data',
  'transformed_train_dir': 'train',
  'transformed_test_dir': 'test',
  'preprocessing_dir': 'preprocessed',
  'preprocessed_object_file_name': 'preprocessed.pkl'},
 'model_trainer_config': {'trained_model_dir': 'trained_model',
  'model_file_name': 'model.pkl',
  'base_accuracy': 0.6},
 'model_evaluation_config': {'model_evaluatio

In [18]:
config_info["data_ingestion_config"].

{'dataset_download_url': 'https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.tgz',
 'raw_data_dir': 'raw_data',
 'tgz_download_dir': 'tgz_data',
 'ingested_dir': 'ingested_data',
 'ingested_train_dir': 'train',
 'ingested_test_dir': 'test'}

In [44]:
data = None
with open(config_file_path,"r") as f:
    data = f.readlines()

In [47]:
data

['training_pipeline_config:\n',
 '  pipeline_name: housing\n',
 '  artifact_dir: artifact\n',
 '\n',
 'data_ingestion_config:\n',
 '  dataset_download_url: https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.tgz\n',
 '  raw_data_dir: raw_data\n',
 '  tgz_download_dir: tgz_data\n',
 '  ingested_dir: ingested_data\n',
 '  ingested_train_dir: train\n',
 '  ingested_test_dir: test \n',
 '\n',
 '\n',
 '\n',
 '\n',
 'data_validation_config:\n',
 '  schema_dir : config\n',
 '  schema_file_name: schema.yaml\n',
 '  report_file_name : report.json\n',
 '  report_page_file_name : report.html\n',
 '\n',
 'data_transformation_config:\n',
 '  add_bedroom_per_room: True\n',
 '  transformed_dir: transformed_data\n',
 '  transformed_train_dir: train\n',
 '  transformed_test_dir: test\n',
 '  preprocessing_dir: preprocessed\n',
 '  preprocessed_object_file_name: preprocessed.pkl\n',
 '  \n',
 'model_trainer_config:\n',
 '  trained_model_dir: trained_model\n',
 '  model_fi

In [1]:
os.getcwd()

'd:\\ML Projects\\house_price_prediction\\notebook'

In [2]:
os.chdir("d:\\ML Projects\\house_price_prediction")

In [3]:
os.getcwd()

'd:\\ML Projects\\house_price_prediction'

In [4]:
os.listdir()

['.dockerignore',
 '.git',
 '.github',
 '.gitignore',
 'app.py',
 'config',
 'demo.py',
 'Dockerfile',
 'house_price_prediction.egg-info',
 'housing',
 'housing_logs',
 'LICENSE',
 'notebook',
 'README.md',
 'requirements.txt',
 'setup.py',
 'venv']

In [5]:
os.getcwd()

'd:\\ML Projects\\house_price_prediction'

In [6]:
from housing.config.configuration import Configuration

In [7]:
config = Configuration()

In [8]:
config.config_info

{'training_pipeline_config': {'pipeline_name': 'housing',
  'artifact_dir': 'artifact'},
 'data_ingestion_config': {'dataset_download_url': 'https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.tgz',
  'raw_data_dir': 'raw_data',
  'tgz_download_dir': 'tgz_data',
  'ingested_dir': 'ingested_data',
  'ingested_train_dir': 'train',
  'ingested_test_dir': 'test'},
 'data_validation_config': {'schema_dir': 'config',
  'schema_file_name': 'schema.yaml',
  'report_file_name': 'report.json',
  'report_page_file_name': 'report.html'},
 'data_transformation_config': {'add_bedroom_per_room': True,
  'transformed_dir': 'transformed_data',
  'transformed_train_dir': 'train',
  'transformed_test_dir': 'test',
  'preprocessing_dir': 'preprocessed',
  'preprocessed_object_file_name': 'preprocessed.pkl'},
 'model_trainer_config': {'trained_model_dir': 'trained_model',
  'model_file_name': 'model.pkl',
  'base_accuracy': 0.6},
 'model_evaluation_config': {'model_evaluatio

In [9]:
config.get_training_pipeline_config()

TrainingPipelineConfig(artifact_dir='d:\\ML Projects\\house_price_prediction\\housing\\artifact')

In [10]:
config.get_data_ingestion_config()

DataIngestionConfig(dataset_download_url='https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.tgz', raw_data_dir='d:\\ML Projects\\house_price_prediction\\housing\\artifact\\data_ingestion\\2022-07-07_22-03-09\\raw_data', tgz_download_dir='d:\\ML Projects\\house_price_prediction\\housing\\artifact\\data_ingestion\\2022-07-07_22-03-09\\tgz_data', ingested_dir='d:\\ML Projects\\house_price_prediction\\housing\\artifact\\data_ingestion\\2022-07-07_22-03-09\\ingested_data', ingested_train_dir='d:\\ML Projects\\house_price_prediction\\housing\\artifact\\data_ingestion\\2022-07-07_22-03-09\\ingested_data\\train', ingested_test_dir='d:\\ML Projects\\house_price_prediction\\housing\\artifact\\data_ingestion\\2022-07-07_22-03-09\\ingested_data\\test')

In [1]:
class tcc:
    def __init__(self,x):
        self.x=x
    def abc(self):
        a = 5
        b = 'sumit'
        c = 6
        result = a*c
        return result

    def cde(self):
        result = self.abc()

        f = result-8

        return f

In [4]:
t =tcc(5)

In [5]:
t.abc()

30

In [6]:
t.cde()

22

In [1]:
os.getcwd()

'd:\\ML Projects\\house_price_prediction\\notebook'

In [35]:
os.chdir("d:\\ML Projects\\house_price_prediction")

In [36]:
os.getcwd()

'd:\\ML Projects\\house_price_prediction'

In [41]:
os.listdir("config")[0]

'config.yaml'

In [5]:
os.path.exists("config")

True

In [9]:
os.getcwd()

'd:\\ML Projects\\house_price_prediction'

In [1]:
file_path = r"D:\ML Projects\house_price_prediction\raw_data\housing.csv"

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv(file_path)

In [8]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [5]:
df.shape

(20640, 10)

In [6]:
from sklearn.model_selection import StratifiedShuffleSplit

In [10]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [12]:
import numpy as np

In [17]:
df["Income_cat"] = pd.cut(df["median_income"],bins=[0 , 1.5 , 3.0 , 4.5 , 6.0 , np.inf],labels =[1,2,3,4,5])

In [15]:
df['income_cat'] = pd.cut(
                df["median_income"],
                bins=[0, 1.5, 3.0, 4.5, 6.0, np.inf],
                labels = [1,2,3,4,5])

In [23]:
df.drop(columns ="income_cat",inplace = True)

In [24]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity Income_cat  
0            NEAR BAY          5  
1            NEAR BAY          5  
2            NEAR BAY          5  
3            NEAR BAY          4  
4            NEAR BAY          3  
...               ...        ...  
20635          INLAND          2  
20636          INLAND          2  
20637          INLAND          2  
20638          INLAND          2  
20639          INLAND          2  

[20640 rows x 11 columns]

In [27]:
split = StratifiedShuffleSplit(n_splits=2,test_size=0.20,random_state=42)

In [30]:
for train_index , test_index in split.split(df,df["Income_cat"]):
    print(train_index)

[12655 15502  2908 ... 19263 19140 19773]
[13027  9783 19268 ...  7576  5912  3909]


In [32]:
print(test_index)

[12161  3624 19942 ...  4285 10098   956]


In [33]:
print(train_index)

[13027  9783 19268 ...  7576  5912  3909]
